theme = "awesome-identity"
baseURL = ""
title = "BeYoung ğŸ˜‡âœŒğŸ»"


## Profile Configurations
[params.profile]
  portrait = "/images/abc.jpg"
  color = rgb(87, 96, 255)
  firstname = "Benson"
  lastname = "Yeung"
  title = "Student / Data Analyst"
  bio = """John Smith brings over 40 years experience leading, contributing to, and growing engineering organizations in top [**VR**](https://en.wikipedia.org/wiki/Virtual_reality) technology companies.

  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas et lacinia metus. Aliquam venenatis, orci ornare mollis congue, mi arcu lobortis tellus, id pulvinar ex ante eu mauris.

  Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.
  """
[params.contacts]
  email = "bensonyeung013@gmail.com"
  instagram = "bennsoonnn"
## Footer Configurations
[params.footer]
  copyright = "Â© 2019 Byungjin Park. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
